---
title: "TidyTuesday 2021/w41 - Seafood producton"
author: "@javierfs"
date: "12th of October 2021"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
                      dev = "ragg_png", res = 500, retina = 1)

library(tidyverse)
library(camcorder)
library(poissoned)
library(extrafont)
library(ggstream)
library(wesanderson)
library(showtext)
library(scales)
library(colorspace)
library(pdftools)
library(ragg)
library(ggrepel)

font_add_google(name = "Bebas Neue", family = "bebas-neue")
font_add_google(name = "Montserrat", family = "montserrat")

showtext_auto() 


```

```{r}
# Get the Data

# Read in with tidytuesdayR package 
# Install from CRAN via: install.packages("tidytuesdayR")
# This loads the readme and all the datasets for the week of interest

# Either ISO-8601 date or year/week works!

tuesdata <- tidytuesdayR::tt_load('2021-10-12')
tuesdata <- tidytuesdayR::tt_load(2021, week = 42)


farmed <- tuesdata$`aquaculture-farmed-fish-production`
captured_vs_farmed <-tuesdata$`capture-fisheries-vs-aquaculture`
captured <- tuesdata$`capture-fishery-production`
consumption <- tuesdata$`fish-and-seafood-consumption-per-capita`
stock <- tuesdata$`fish-stocks-within-sustainable-levels`
fishery <- tuesdata$`global-fishery-catch-by-sector`
production <- tuesdata$`seafood-and-fish-production-thousand-tonnes`

```


```{r}
#Discarding continents and regions: assuming they are aggregates of countries
top_production_entities_fish_type <- production  %>% 
  filter(!Entity %in% c('Americas', 'Asia', 'Europe', 'Eastern Asia', 'European Union', 'South Eastern Asia', 'Southern Europe', 'Northern Europe', 'Eastern Europe', 'Northern America', 'World', 'Africa', 'Southern Asia', 'Net Food Importing Developing Countries', 'Low Income Food Deficit Countries', 'Least Developed Countries', 'South America','Indonesia', 'USSR', 'Eastern Africa', 'Europe, Western', 'Land Locked Developing Countries')) %>% 
  pivot_longer(4:last_col(), names_to = "fish", values_to = "tonnes")  %>% 
  janitor::clean_names() %>% 
  mutate(
    fish = str_extract(fish, "(?<=lent - ).+(?= - 27)"), # Extract seafood names from column names
    fish = str_remove(fish, ",.+")) %>% 
  group_by(entity) %>% 
  summarise(median_production_tonnes = median(tonnes)) %>% 
  top_n(5, median_production_tonnes) %>% 
  arrange(desc(median_production_tonnes))

top_production_year_fish_type <- production %>% 
  pivot_longer(4:last_col(), names_to = "fish", values_to = "tonnes")  %>% 
  janitor::clean_names() %>% 
  mutate(
    # Extract seafood names from column names
    fish = str_extract(fish, "(?<=lent - ).+(?= - 27)"),
    fish = str_remove(fish, ",.+")) %>% 
  merge(top_production_entities_fish_type, by= c('entity'))




  
```

```{r}
pal1 <- c('#14505C', '#2A7979', '#4CA38F', '#81CA9F','#C7E5BE')
countries <- c("China","India","Japan","Thailand","United States") 

g <- top_production_year_fish_type %>%
  mutate(year= as.Date(ISOdate(year, 1, 1)),
         entity= factor(entity, levels= countries)) %>%
    ggplot(aes(x = year, 
             y= tonnes, 
             fill = entity,
             label = entity)) +
  geom_stream(extra_span = 0.2, 
              true_range ='none', 
              type = "mirror", 
              n_grid = 1000, 
              bw = .75,
              lwd = 0) +
  facet_wrap(~fish , 
             ncol = 1, 
             scales = "free_y",
             strip.position = 'left')+
  cowplot::theme_minimal_vgrid(font_size = 18) +
  theme(legend.position = "none") +
  scale_colour_manual(values = pal1 %>% colorspace::darken(.8)) +
  scale_fill_manual(values = pal1) +
  scale_y_continuous(labels = label_number_si(), position = "right")+ 
  scale_x_date(breaks = seq(as.Date("1960-01-01"), as.Date("2013-01-01"), by="10 years"), 
               date_labels = "%Y") +
  theme_minimal()+
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        legend.key.size =unit(rel(.5), "cm"),
        legend.box = "horizontal",
        legend.title = element_blank(),
        legend.text = element_text(size=rel(1.5)),
        plot.background = element_rect(fill = '#F6FBF4', color = NA),
        panel.grid.major.x = element_line(size = 0.15, color = lighten('#14505C', 0.3)),
        panel.grid.major.y = element_blank(),
        panel.border = element_blank(),
        panel.grid.minor = element_blank(),
        text = element_text(family = "bebas-neue",
                            color = 'black'),
        plot.title = element_text(size = rel(4.5), 
                                  color = 'black',
                                  family= "bebas-neue",
                                  hjust = 0.5),
        plot.subtitle = element_text(size = rel(3), 
                                     color = 'black',
                                     family= "bebas-neue",
                                     hjust = 0.5),
        plot.caption = element_text(size = rel(1), 
                                     color = 'black',
                                     family= "montserrat",
                                     ),
        strip.text.y = element_text(size = rel(2.5), 
                                     color = 'black',
                                     family= "montserrat"),
        axis.text.x = element_text(size=rel(2.5),
                                    color = 'black',
                                    family = 'montserrat'),
        axis.text.y = element_text(size=rel(2),
                                    color = 'black',
                                    family = 'montserrat'),
        axis.title.y = element_blank(),
        axis.title.x = element_blank()
        )+
  guides(color = guide_legend(title.position = "bottom", 
                              # hjust = 0.5 centres the title horizontally
                              title.hjust = 0.5,
                              label.position = "bottom")) +
   labs(
      title = "Top production countries: fish species",
      subtitle = "1960 - 2013",
      caption = "Production measured in tonnes | made by: @javierfs | Data Source: OurWorldinData.org "
   
    ) 


ggsave(here::here('w41-2021-10-12', "plots", paste0("w41_globalfish-", format(Sys.time(), "%Y%m%d_%H%M%S"), ".png")), dpi = 320, height = 6, width = 4)

  
```

